### ISSUE TITLE
`npm run lint` seems to be returning SCSS linting errors (but not failing CI?)

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1507] opened 2022-07-29 10:58 UTC
On `master`, I ran `npm i` and then `npm run lint` and it results in 3936 linting errors (sample in screenshot). But, interestingly, none of these errors fail CI?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/2828721/181745512-3a8d7c9a-9858-4d5d-b3be-10462c9f5035.png">

**AC**
* Verify linting errors fail CI before PR merge
* Verify whether we need to fix/ignore the SCSS linting errors returned.

**Comment by viktorrusakov** [comment] 2022-08-05 07:37
Hmm, we couldn't reproduce this locally, also I don't see any warnings in CI jobs that do linting check. Are you sure you were on the latest master and didn't have any changes in `.eslitrc`?

**Comment by viktorrusakov** [comment] 2022-10-09 08:48
Closing this since the issue is not reproduced anywhere.

**Closed by viktorrusakov** 2022-10-09 08:48 UTC
