### ISSUE TITLE
Make sure all display string props accept element proptype

### ISSUE THREAD

**Issue by thallada** [openedx/paragon#224] opened 2018-04-26 15:59 UTC
Studio-frontend needs to be able to pass in an element wherever a component accepts a display string because it wraps all translated string in a span that specifies the language of the translation e.g. `<span lang="en">`.

**Comment by jaebradley** [comment] 2018-04-30 17:54
I would argue that this is what `props.children` should be used for

```javascript
<MyComponent>
  blahbblahblah
</MyComponent>
```

and

```javascript
<MyComponent>
 <span>blahblahblah</span>
</MyComponent>
```

**Comment by thallada** [comment] 2018-04-30 18:54
If we do that, then we will loose the ability to enforce certain accessible patterns. Like [requiring a `legend` on a `Fieldset`](https://github.com/edx/paragon/tree/master/src/Fieldset#legend-string-or-element-required), a [`label` on an `asInput`](https://github.com/edx/paragon/tree/master/src/asInput#label-string-or-element-required), and a [description for the danger theme validation icon on `asInput` and `Fieldset`](https://github.com/edx/paragon/tree/master/src/asInput#dangericondescription-string-or-element-optional). Getting rid of those props would mean that it would be up to the consumer of Paragon to make sure to include them in the `children`. Is that the direction that we want to go in?

**Comment by thallada** [comment] 2018-05-11 20:17
As Jae pointed out, we should rename the `closeText` prop on the `Modal` to something that implies that it accepts a string or an element. `closeLabel` maybe?

**Comment by jaebradley** [comment] 2018-05-11 20:25
Again, I feel like this API might be more intuitive

```javascript
<Modal>
  <Title>
    Some title
  </Title>
  <Body>
    Some body
  </Body>
  <Label>
    Some label
  </Label>
</Modal>
```

I think we should think about using `children` instead of jamming things into `props`.

**Comment by fysheets** [comment] 2018-05-11 20:34
How do we enforce certain components/aria attributes that are needed for accessibility become children then? I feel like that could lead to regressions in accessibility due to folks *needing* to know all required children instead of having them by default and providing the text (element for i18n) and more or less getting the accessibility out of the box. That sort of change feels to me like we're doing a component library, but not necessarily an accessible one which I thought was one of the main appeals of Paragon and a goal to help prevention of regressions as we move forward.

**Comment by jaebradley** [comment] 2018-05-11 20:36
Well when you iterate through the children you can check their types. 

If, for a modal, you iterate through all the children and a `Label` has not been found then you can throw / `console.log` an error, or create one by default.

**Comment by fysheets** [comment] 2018-05-11 20:57
Personally, I don't trust that a console error will prevent these types of regressions moving forward - anyone can 100% ignore messages in the console, merge, and **maybe** "come back to it later." Especially since this sort of functionality is already there by default, removing it for a console log solution seems like a very risky trade-off.

To your your second point of creating the missing child by default, how do we know what the default values should be at that point? If nothing is being sent in, creating a default seems like we would be making many assumptions for what the implementer was intending without getting more information from them, which again increases risk. Also, aren't we already creating these defaults today, but giving the option for providing us with the context, information, customization with the props.

This hypothetical validation that will be looping though the passed in children would also have to have logic involved for proper aria-attributes (labels/describedby/hidden/etc) on each required child that we would need to know in advance by in order to ensure accessibility. That amount of logic and forward thinking maintenance to handle this for every optional case of "you can pass in any children at all and we will validate it with this loop" seems rather high instead of allowing folks to pass in a string or element as a prop (that is predominantly for i18n or Icons currently) for specific component features that explicitly exist and that provide a linting catch on the prop type validation prior to the merge occurring.

Overall I'm not sure the tradeoffs are worth the amount of effort involved for pretty much overhauling the components altogether. This change initially called for expanding functionality of existing props and ensuring their names are handled correctly, which overall is a light lift and a quick win. I'm happy to chat more, but so far I'm not 100% convinced.

**Comment by jaebradley** [comment] 2018-05-11 21:15
> Personally, I don't trust that a console error will prevent these types of regressions moving forward - anyone can 100% ignore messages in the console, merge, and maybe "come back to it later."

Sure, so I guess, throw an Error then? 

This is how `PropType` violations are seen - at runtime, in development mode, as console error statements - and they're supposed to define part of the API for your component.

I am unsure how a similar validation system (if not a stricter validation system, by actually throwing exceptions) wouldn't be useful for communicating 95% of all API misuse to the implementer. 

> how do we know what the default values should be at that point?

Well, we have a default prop value for `closeText` right?

I'm just saying that we should move the API from being `prop`-based to being `children`-based.

I don't see how you lose that customization with a more declarative `children`-based API. You're just moving the API entry point from a `prop` to a `child`.

> That amount of logic and forward thinking maintenance to handle this...seems rather high

I think most really good APIs generally have a decent amount of abstracted logic to make using the actual API as intuitive as possible.

**Comment by fysheets** [comment] 2018-05-11 22:15
I'm not trying to generally disagree with your suggestion, the context that I'm missing here and what I was looking for with my discussion points is: what is the value-add of changing the the APIs in this way and how does that compare to the value-add of the original suggested solution? I know the scope of this issue was initially thought of in the view of being able to support i18n within the text of Paragon components. I'm assuming that your change suggestion goes after a larger scope of benefit and I'd like to understand that viewpoint to weigh the benefits vs tradeoffs of the two proposed solutions that we have.

**Comment by adamstankiewicz** [comment] 2022-03-27 18:48
This is being handled by ongoing work to add native i18n support via react-intl to Paragon. Closing.

**Closed by adamstankiewicz** 2022-03-27 18:48 UTC
