### ISSUE TITLE
Displaying the skeleton component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2420] opened 2023-07-05 12:16 UTC
After changing the background of the use cases on the documentation site, there was a problem with the display of loading bars in the [Skeleton component](https://paragon-openedx.netlify.app/components/skeleton/).

![image](https://github.com/openedx/paragon/assets/93188219/e7b07bfb-91ee-44b5-95b0-ebe9e85d503b)

![image](https://github.com/openedx/paragon/assets/93188219/4ced6906-3f05-4008-ab05-787b65a21588)

**Comment by adamstankiewicz** [comment] 2023-07-12 13:03
@PKulkoRaccoonGang Great catch. A couple thoughts here:

1. Is this a bug only on the documentation website? Or is it also an issue for consumers of `Skeleton` (e.g., in MFEs)?
1. Are we sure the issue is due to the changed background color of the code block previews?
    1. Presumably, the "With custom theme" example code snippet would have distinct background color from the background of the code block preview but it also does not appear.
    1. There was also a [recent change](https://github.com/openedx/paragon/pull/2362) related to how we import the CSS from `react-loading-skeleton`, which I feel may be more of the culprit to the regression we're now seeing in the documentation website. Looking at the deploy preview on that change to the CSS import, the skeleton loaders are not visible on the docs site, but a [deploy preview for just 2 PRs earlier](https://deploy-preview-2360--paragon-openedx.netlify.app/components/skeleton/) from that recent change, the skeleton loaders do appear on the colored background (/cc @davidjoy):

<img width="969" alt="image" src="https://github.com/openedx/paragon/assets/2828721/455b15d4-cd3b-489c-b832-73488570f301">

**Comment by adamstankiewicz** [comment] 2023-08-04 13:21
1. Find solution.
2. Verify in Gatsby docs site.
3. Verify in example Paragon MFE.
4. Check in consuming MFE.

**Comment by adamstankiewicz** [comment] 2023-08-11 12:16
I believe this recently filed `Card` [loading state issue](https://github.com/openedx/paragon/issues/2528) will likely be resolved by this issue.

**Comment by PKulkoRaccoonGang** [comment] 2023-08-16 11:23
PR: https://github.com/openedx/paragon/pull/2531

**Comment by viktorrusakov** [comment] 2023-12-21 09:04
This was fixed in https://github.com/openedx/paragon/pull/2865

**Closed by viktorrusakov** 2023-12-21 09:04 UTC
Labels: bug, raccoon-gang
